// <auto-generated />
using System;
using System.Collections.Generic;
using LLMProxy.Infrastructure.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LLMProxy.Infrastructure.PostgreSQL.Migrations
{
    [DbContext(typeof(LLMProxyDbContext))]
    [Migration("20251221031424_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LLMProxy.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_key_hash");

                    b.HasIndex("KeyPrefix")
                        .HasDatabaseName("ix_api_keys_key_prefix");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_api_keys_tenant_id");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_api_keys_user_active");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("client_ip");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("text")
                        .HasColumnName("error_stack_trace");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("http_method");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymized");

                    b.Property<bool>("IsError")
                        .HasColumnType("boolean")
                        .HasColumnName("is_error");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text")
                        .HasColumnName("request_body");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("request_id");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("request_path");

                    b.Property<long>("RequestTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("request_tokens");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<long>("ResponseTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("response_tokens");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_tokens");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_audit_logs_request_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_audit_logs_tenant");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_tenant_created");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.Entities.LLMProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_llm_providers");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_llm_providers_priority");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_llm_providers_tenant_active");

                    b.ToTable("llm_providers", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.Entities.QuotaLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<long>("Limit")
                        .HasColumnType("bigint")
                        .HasColumnName("limit");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.Property<int>("QuotaType")
                        .HasColumnType("integer")
                        .HasColumnName("quota_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_quota_limits");

                    b.HasIndex("UserId", "QuotaType", "Period")
                        .IsUnique()
                        .HasDatabaseName("ix_quota_limits_user_type_period");

                    b.ToTable("quota_limits", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.Entities.TokenUsageMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AverageDurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("average_duration_ms");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("estimated_cost");

                    b.Property<long>("FailedRequests")
                        .HasColumnType("bigint")
                        .HasColumnName("failed_requests");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<long>("SuccessfulRequests")
                        .HasColumnType("bigint")
                        .HasColumnName("successful_requests");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("total_duration_ms");

                    b.Property<long>("TotalInputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_input_tokens");

                    b.Property<long>("TotalOutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_output_tokens");

                    b.Property<long>("TotalRequests")
                        .HasColumnType("bigint")
                        .HasColumnName("total_requests");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_tokens");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_token_usage_metrics");

                    b.HasIndex("ProviderId", "PeriodStart")
                        .HasDatabaseName("ix_token_metrics_provider_period");

                    b.HasIndex("UserId", "PeriodStart")
                        .HasDatabaseName("ix_token_metrics_user_period");

                    b.HasIndex("TenantId", "PeriodStart", "Period")
                        .HasDatabaseName("ix_token_metrics_tenant_period");

                    b.HasIndex("TenantId", "UserId", "ProviderId", "PeriodStart", "Period")
                        .IsUnique()
                        .HasDatabaseName("ix_token_metrics_unique_key");

                    b.ToTable("token_usage_metrics", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("LLMProxy.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_tenants_tenant_id");

                    b.HasOne("LLMProxy.Domain.Entities.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LLMProxy.Domain.Entities.LLMProvider", b =>
                {
                    b.HasOne("LLMProxy.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Providers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_llm_providers_tenants_tenant_id");

                    b.OwnsOne("LLMProxy.Domain.Entities.ProviderConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("LLMProviderId")
                                .HasColumnType("uuid")
                                .HasColumnName("llmprovider_id");

                            b1.Property<string>("ApiKeySecretName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("api_key_secret_name");

                            b1.Property<string>("CertificateSecretName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("certificate_secret_name");

                            b1.Property<Dictionary<string, string>>("Headers")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("headers");

                            b1.Property<int>("MaxRetries")
                                .HasColumnType("integer")
                                .HasColumnName("max_retries");

                            b1.Property<bool>("RequiresCertificate")
                                .HasColumnType("boolean")
                                .HasColumnName("requires_certificate");

                            b1.Property<bool>("SupportsStreaming")
                                .HasColumnType("boolean")
                                .HasColumnName("supports_streaming");

                            b1.Property<int>("TimeoutSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("timeout_seconds");

                            b1.HasKey("LLMProviderId")
                                .HasName("pk_llm_provider_configurations");

                            b1.ToTable("llm_provider_configurations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LLMProviderId")
                                .HasConstraintName("fk_llm_provider_configurations_llm_providers_llmprovider_id");
                        });

                    b.OwnsOne("LLMProxy.Domain.Entities.RoutingStrategy", "RoutingStrategy", b1 =>
                        {
                            b1.Property<Guid>("LLMProviderId")
                                .HasColumnType("uuid")
                                .HasColumnName("llmprovider_id");

                            b1.Property<string>("HeaderName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("routing_header_name");

                            b1.Property<int>("Method")
                                .HasColumnType("integer")
                                .HasColumnName("routing_method");

                            b1.Property<string>("PathPattern")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("routing_path_pattern");

                            b1.Property<string>("Subdomain")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("routing_subdomain");

                            b1.HasKey("LLMProviderId")
                                .HasName("pk_llm_provider_routing_strategies");

                            b1.ToTable("llm_provider_routing_strategies", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LLMProviderId")
                                .HasConstraintName("fk_llm_provider_routing_strategies_llm_providers_llmprovider_id");
                        });

                    b.Navigation("Configuration")
                        .IsRequired();

                    b.Navigation("RoutingStrategy")
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LLMProxy.Domain.Entities.QuotaLimit", b =>
                {
                    b.HasOne("LLMProxy.Domain.Entities.User", "User")
                        .WithMany("QuotaLimits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quota_limits_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LLMProxy.Domain.Entities.Tenant", b =>
                {
                    b.OwnsOne("LLMProxy.Domain.Entities.TenantSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<int>("AuditRetentionDays")
                                .HasColumnType("integer")
                                .HasColumnName("audit_retention_days");

                            b1.Property<bool>("EnableAuditLogging")
                                .HasColumnType("boolean")
                                .HasColumnName("enable_audit_logging");

                            b1.Property<bool>("EnableResponseCache")
                                .HasColumnType("boolean")
                                .HasColumnName("enable_response_cache");

                            b1.Property<int>("MaxProviders")
                                .HasColumnType("integer")
                                .HasColumnName("max_providers");

                            b1.Property<int>("MaxUsers")
                                .HasColumnType("integer")
                                .HasColumnName("max_users");

                            b1.HasKey("TenantId")
                                .HasName("pk_tenant_settings");

                            b1.ToTable("tenant_settings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TenantId")
                                .HasConstraintName("fk_tenant_settings_tenants_tenant_id");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("LLMProxy.Domain.Entities.User", b =>
                {
                    b.HasOne("LLMProxy.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LLMProxy.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Providers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LLMProxy.Domain.Entities.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("QuotaLimits");
                });
#pragma warning restore 612, 618
        }
    }
}
